services:
  web:
    build: .
    container_name: rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - ./data/.:/app/data/
    environment:
      RAILS_LOG_TO_STDOUT: 1
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:sequra_development@db:5432/sequra_development
      REDIS_URL: redis://redis:6379/1
      DB_SETUP_ON_START: "true"
  db:
    build:
      dockerfile: Dockerfile.postgres
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sequra_development
      POSTGRES_DB: sequra_development
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  sidekiq:
    build: .
    container_name: sidekiq
    environment:
      REDIS_URL: redis://redis:6379/1
      DATABASE_URL: postgres://postgres:sequra_development@db:5432/sequra_development
    depends_on:
      - web
    command: bundle exec sidekiq
  spec:
    build: .
    container_name: spec
    environment:
      RAILS_LOG_TO_STDOUT: 1
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:sequra_test@db-test:5432/sequra_test
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - db-test
    entrypoint: /app/entrypoint-test.sh

  db-test:
    build:
      dockerfile: Dockerfile.postgres
    container_name: db-test
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sequra_test
      POSTGRES_DB: sequra_test
    depends_on:
      - db

volumes:
  postgres_data:
  postgres_test_data:
